{% set python_min = '3.10.0' %}
{% set name = "gym-pusht" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gym_pusht-{{ version }}.tar.gz
  sha256: 981e135f6e0ca91e4ec63603e9551bc77cba989d06a2888ed31a1d68f7cbdae2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - gymnasium >=0.29.1
    - opencv >=4.9.0
    - pygame >=2.5.2
    - pymunk >=6.6.0
    - shapely >=2.0.3
    - scikit-image >=0.22.0
  run_constrained:
    - pre-commit >=3.7.0
    - debugpy >=1.8.1
    - pytest >=8.1.0
    - pytest-cov >=5.0.0

test:
  imports:
    - gym_pusht
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/huggingface/gym-pusht
  summary: A gymnasium environment for PushT.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
